-- Section 1 — Joins (Basic to Intermediate)

-- 1. Display all orders with customer names.
select o.OrderID, c.CustomerName
from Orders as o
join Customers as c ON o.CustomerID = c.CustomerID;

-- 2. Show product names and quantities for each order.
select od.productid, od.quantity, p.ProductName
from orderdetails as od
join products as p ON od.ProductID=p.ProductID;

-- 3. Display employee name who handled each order.

select o.OrderID,o.EmployeeID, e.EmployeeName
from orders as o
join employees as e ON o.EmployeeID=e.EmployeeID;

-- 4. Show all customers and their orders (including customers without orders).

select c.customerID, c.CustomerName, o.OrderID, o.orderdate
from customers as c
Left join orders as o ON c.CustomerID=o.CustomerID;

-- 5. Display total number of orders handled by each employee.

select e.employeeid, e.employeename, count(o.orderID) as TotalOrders
from employees as e
left join Orders as o ON e.EmployeeID=o.EmployeeID
group by e.employeeid,e.employeename;

-- Section 2 — Subqueries

-- 6. Find customers who placed more than 1 order.

select c.customerid,c.customername, count(o.orderid) as OrderCount
from customers as c
left join Orders as o ON c.CustomerID=o.CustomerID
group by c.CustomerID,c.CustomerName
having count(o.orderid)>1;

-- 7. Display products with price higher than the average product price.

select ProductID,productname, price 
from products 
where price>(select avg(Price) from products);

-- 8. Find the customer who placed the highest number of orders.

select  c.customerid,c.customername,count(o.orderid) as OrderCount
from customers as c
join Orders as o ON c.customerID=o.CustomerID
group by c.customerid,c.customername
order by OrderCount desc
limit 1;

-- 9. Show orders where total quantity is greater than the average quantity.

select orderid,sum(quantity) as TotalQuantity 
from orderdetails
group by orderid
having sum(quantity)>(select avg(quantity) from orderdetails);

-- 10. Find employees who handled more orders than the average employee.

select o.employeeid,count(o.orderid) as OrderCount 
from Orders as o
group by o.employeeid
having count(o.orderid)>(select avg(ordercount) 
                         from (select count(orderid) as ordercount 
                                from orders group by employeeid) as EmployeeOrders);
                                

-- Section 3 — CTE (Common Table Expressions)

-- 11. Using CTE, calculate total sales amount for each order.

-- Expected logic:

-- Quantity × Price

with OrderSales as (
		select od.orderid, sum(od.quantity*p.price) as TotalSalesAmount 
        from orderdetails as od 
        join products as p ON od.ProductID=p.ProductID
        group by od.orderid)
        
select OrderID,TotalSalesAmount from OrderSales;

-- 12. Using CTE, find customers whose total purchase amount is greater than 20,000.

with PurchaseAmount as (
						select o.customerid, sum(od.quantity*p.price) as TotalPurchaseAmount
                        from orderdetails as od
                        join products as p ON od.ProductID=p.ProductID
                        join orders as o ON od.orderid=o.orderid
                        group by o.CustomerID)
                        
select c.customerid,c.customername,pa.TotalPurchaseAmount 
from PurchaseAmount as pa 
join Customers as c ON pa.customerid=c.customerid
where pa.TotalPurchaseAmount>20000;

-- 13. Using CTE, display the total revenue generated by each product category.

with productsales as (
						select p.category,sum(od.quantity*p.price)as TotalRevenue
                        from orderdetails as od
                        join products as p ON od.ProductID=p.ProductID
                        group by p.Category)
					
select category,TotalRevenue from productsales;

-- 14. Using CTE, find the top 3 customers based on total spending.

with customerspend as (
						select c.customerid,c.customername,sum(od.quantity*p.price) as TotalSpend
                        from customers as c
                        join orders as o ON c.CustomerID=o.CustomerID
                        join orderdetails as od ON od.orderid=o.orderid
                        join products as p ON od.ProductID=p.productid
                        group by c.customerid,c.CustomerName)
select customerid,customername,TotalSpend from customerspend 
order by TotalSpend Desc
limit 3;
		
-- Section 4 — Window Functions
 
-- 15. Assign rank to customers based on total purchase amount.

-- Use:

-- RANK()

with customerspend as (
						select c.customerid,c.customername,sum(od.quantity*p.price) as TotalSpend
                        from customers as c
                        join orders as o ON c.CustomerID=o.CustomerID
                        join orderdetails as od ON od.orderid=o.orderid
                        join products as p ON od.ProductID=p.productid
                        group by c.customerid,c.CustomerName)
select customerid,customername,TotalSpend, Rank() over(order by TotalSpend Desc) as RankPosition from customerspend ;

-- 16. Display cumulative sales amount by order date.

-- Use:

-- SUM() OVER

with OrderSales as (
		select o.orderid,o.orderdate, sum(od.quantity*p.price) as TotalSalesAmount 
        from Orders as o
        join orderdetails as od ON o.orderid=od.OrderID
        join products as p ON od.ProductID=p.ProductID
        group by o.orderid,o.orderdate)
        
select OrderID,orderdate,TotalSalesAmount, sum(TotalSalesAmount) 
           over(order by orderdate) as CumulativeSales 
           from OrderSales
           order by orderdate;
-- 17. Display running total of sales for each employee.
-- Use:

-- PARTITION BY EmployeeID

with EmployeeSales as ( 
						select o.employeeid, o.orderdate,o.orderid,
                        sum(od.quantity*p.price) as TotalSales
                        from orders as o
                        join orderdetails as od ON o.OrderID=od.OrderID
                        join products as p ON od.ProductID=p.ProductID
                        group by o.orderid,o.OrderDate)
                        
select employeeid,orderid,orderdate,TotalSales, sum(TotalSales)
over( partition by Employeeid order by orderdate) as RunningTotal
from EmployeeSales
order by employeeid,orderdate;

-- 18. Find the highest priced product in each category.

-- Use:

-- ROW_NUMBER()

select category,productname, price from (
		select category,productname,price,row_number() over(partition by category order by price desc) as rn 
        from products) as ranked
        where rn=1;
        
-- Optional Bonus Tasks (Advanced — if you want to challenge stronger students)

-- 21. Find customers who never placed an order.

select c.customerid, c.customername
from customers as c
left join orders as o ON c.CustomerID=o.CustomerID
where o.orderid is null;

-- 22. Find the second highest selling product.

select productid,productname,TotalSales 
from( select p.productid,productname,sum(od.quantity) as TotalSales , 
       row_number() over ( order by sum(od.quantity) desc ) as  rn
       from products as p
       inner join orderdetails as od on p.productid=od.productid
       group by p.ProductID,p.ProductName) as ranked
where rn=2;
       
-- 23. Identify duplicate orders placed on the same day.

select o.customerid,o.orderdate,count(o.orderid) as DuplicateCount
from orders as o
group by o.customerid,o.orderdate
having count(o.orderid)>1;



